GET http://localhost:3000

#####register

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "hellods@gmail.com",
    "password": "12#13"
}

#####login

POST http://localhost:3000/auth/login

#####Logout

POST http://localhost:3000/auth/logout

#####refresh-token
POST http://localhost:3000/auth/refresh-token