GET http://localhost:3000
Authorization: Bearer 

#####register

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "sao09sddsds@gmail.com",
    "password": "12#13"
}

#####login

POST http://localhost:3000/auth/login

Content-Type: application/json

{
    "email": "09opsbn@gmail.com",
    "password": "12#13"
}


#####Logout

POST http://localhost:3000/auth/logout

#####refresh-token
POST http://localhost:3000/auth/refresh-token